### ISSUE TITLE
oauth2-proxy auth with ELK does not work

### ISSUE THREAD

**Issue by inetshell** [HobOps/helm-charts#106]
There is a redirect loop.

But if works with this ingress config:
```
  Ingress:
    elk:
      annotations:
        nginx.ingress.kubernetes.io/auth-realm: null
        nginx.ingress.kubernetes.io/auth-secret: null
        nginx.ingress.kubernetes.io/auth-type: null
        nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$escaped_request_uri
        nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
        cert-manager.io/cluster-issuer: letsencrypt
```
