### ISSUE TITLE
Add support to External Secret Operator - PushSecret

### ISSUE THREAD

**Issue by inetshell** [HobOps/helm-charts#88]
@yairavalosHobOps please add support for this component to the common-library.

You can use these files as reference:
- https://github.com/HobOps/helm-charts/blob/main/charts/common-library/templates/ExternalSecretsOperator_ExternalSecret.yaml
- https://github.com/HobOps/helm-charts/blob/main/charts/common-library/templates/_ExternalSecretsOperator_ExternalSecret.yaml
- https://github.com/HobOps/helm-charts/blob/main/charts/common-library/examples/ExternalSecretsOperator_ExternalSecret.yaml

Use this data as example:
```
PushSecret:
  example-push-secret:
    refreshInterval: 1m
    secretStoreRefs:
    - name: aws-parameterstore
      kind: SecretStore
    selector:
      secret:
        name: pokedex-credentials
    data:
    - match:
        secretKey: best-pokemon
        remoteRefs:
        - remoteKey: my-first-parameter
```

Documentation:
https://external-secrets.io/v0.7.2/api/pushsecret/
